# EdgeVision — کلاینت موبایل
# Copyright © 2026 Parsa Fathi — Apache-2.0

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    prefer_single_quotes: true
    unawaited_futures: true
